// <auto-generated />
using System;
using DentLink.DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DentLink.DataAccessLayer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707164747_AddURLimage")]
    partial class AddURLimage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Typies")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.CaseRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TransportCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseRequests");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCardUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.SelectCaseRequest", b =>
                {
                    b.Property<int>("CaseRequestId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("CaseRequestId", "PatientId");

                    b.HasIndex("PatientId");

                    b.ToTable("SelectCaseRequests");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.SendCaseRequest", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("CaseRequestId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId", "CaseRequestId");

                    b.HasIndex("CaseRequestId");

                    b.ToTable("SendCaseRequests");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseRequestId")
                        .HasColumnType("int");

                    b.Property<bool>("PatientArrived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SessionEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SessionStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CaseRequestId")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.Case", b =>
                {
                    b.HasOne("DentLink.DataAccessLayer.Models.Patient", "Patient")
                        .WithMany("Cases")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.CaseRequest", b =>
                {
                    b.HasOne("DentLink.DataAccessLayer.Models.Case", "Case")
                        .WithMany("CaseRequests")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.SelectCaseRequest", b =>
                {
                    b.HasOne("DentLink.DataAccessLayer.Models.CaseRequest", "CaseRequest")
                        .WithMany("SelectCaseRequests")
                        .HasForeignKey("CaseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentLink.DataAccessLayer.Models.Patient", "Patient")
                        .WithMany("SelectCaseRequests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseRequest");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.SendCaseRequest", b =>
                {
                    b.HasOne("DentLink.DataAccessLayer.Models.CaseRequest", "CaseRequest")
                        .WithMany("SendCaseRequests")
                        .HasForeignKey("CaseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentLink.DataAccessLayer.Models.Doctor", "Doctor")
                        .WithMany("SendCaseRequests")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseRequest");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.Session", b =>
                {
                    b.HasOne("DentLink.DataAccessLayer.Models.CaseRequest", "CaseRequest")
                        .WithOne("Session")
                        .HasForeignKey("DentLink.DataAccessLayer.Models.Session", "CaseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseRequest");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.Case", b =>
                {
                    b.Navigation("CaseRequests");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.CaseRequest", b =>
                {
                    b.Navigation("SelectCaseRequests");

                    b.Navigation("SendCaseRequests");

                    b.Navigation("Session")
                        .IsRequired();
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.Doctor", b =>
                {
                    b.Navigation("SendCaseRequests");
                });

            modelBuilder.Entity("DentLink.DataAccessLayer.Models.Patient", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("SelectCaseRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
